# Breast Cancer Detection with PyTorch

This notebook demonstrates a basic breast cancer detection model using a simple neural network in **PyTorch**.

---



## 1. Environment Setup
* **Load Libraries:** Import essential tools including `numpy`, `pandas`, `torch`, and `sklearn`.
* **Load Data:** The breast cancer dataset is loaded from a CSV file into a pandas DataFrame.

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


## 2. Data Preprocessing

* **Splitting:** The data is divided into training and testing sets (`X_train`, `X_test`, `y_train`, `y_test`).
* **Scaling:** Features ($X$) are normalized using `StandardScaler` to ensure the model converges faster.
* **Encoding:** The target variable `diagnosis` (M/B) is converted into numerical labels ($0$ and $1$) using `LabelEncoder`.
* **Tensor Conversion:** Processed NumPy arrays are converted into PyTorch tensors with `float32` dtype.



In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [11]:
len(df.columns)

31

In [12]:
X_train

array([[-0.12745926,  0.73022279,  0.04737896, ...,  1.56293288,
         1.11217228,  3.23278831],
       [-0.16657282,  0.55402282, -0.21269452, ..., -0.81230481,
        -0.74524644, -0.75304238],
       [ 2.54343846,  1.65927721,  2.68445947, ...,  2.34765365,
         0.46934389,  0.19773634],
       ...,
       [-0.3789036 ,  0.66615007, -0.28942428, ...,  1.21765574,
         0.80690955,  2.20432801],
       [ 0.43689361,  0.19018131,  0.41083569, ...,  0.47329203,
         1.75338553,  1.22510252],
       [ 1.06271065,  0.28400207,  1.02467373, ...,  1.21317162,
         0.24645364,  0.05604952]])

In [13]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,

In [14]:
X_train

array([[-0.12745926,  0.73022279,  0.04737896, ...,  1.56293288,
         1.11217228,  3.23278831],
       [-0.16657282,  0.55402282, -0.21269452, ..., -0.81230481,
        -0.74524644, -0.75304238],
       [ 2.54343846,  1.65927721,  2.68445947, ...,  2.34765365,
         0.46934389,  0.19773634],
       ...,
       [-0.3789036 ,  0.66615007, -0.28942428, ...,  1.21765574,
         0.80690955,  2.20432801],
       [ 0.43689361,  0.19018131,  0.41083569, ...,  0.47329203,
         1.75338553,  1.22510252],
       [ 1.06271065,  0.28400207,  1.02467373, ...,  1.21317162,
         0.24645364,  0.05604952]])

In [15]:
type(y_train)

numpy.ndarray

In [16]:
type(y_test)

numpy.ndarray

### Numpy Array to tensors

In [17]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_5065/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_5065/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_5065/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_5065/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recom

In [18]:
type(X_train_tensor)

torch.Tensor

## 3. Model Architecture
* **Define the Model:** A custom class `MySimpleNN` is defined using `nn.Module`.
* **Structure:** The model uses a single **Linear Layer** followed by a **Sigmoid** activation function, which is the standard approach for binary classification.



In [19]:
X_train.shape[1]

30

In [20]:
import torch.nn as nn

In [21]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [22]:
torch.rand(30,1)

tensor([[2.0037e-01],
        [3.9916e-01],
        [9.8195e-01],
        [5.3173e-01],
        [3.0239e-01],
        [9.3275e-01],
        [3.3913e-01],
        [7.5507e-01],
        [6.5213e-01],
        [7.0160e-01],
        [2.6781e-01],
        [8.4572e-02],
        [6.4403e-01],
        [7.7256e-02],
        [2.5177e-04],
        [7.7328e-01],
        [3.6121e-01],
        [8.4773e-01],
        [1.8385e-01],
        [9.4121e-01],
        [7.6462e-01],
        [1.6821e-01],
        [7.2613e-01],
        [4.7963e-01],
        [3.7154e-01],
        [6.4157e-01],
        [8.1585e-01],
        [5.3681e-01],
        [3.7910e-01],
        [6.0123e-01]])

### Parameters

In [23]:
X_train_tensor.shape[1]

30

In [24]:
learning_rate = 0.1
epochs = 25

In [25]:
loss_function = nn.BCELoss()

In [26]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [27]:
model = MySimpleNN(X_train_tensor.shape[1])


In [28]:
model.parameters()

<generator object Module.parameters at 0x7908842d4740>

In [29]:
X_test_tensor.dtype

torch.float32

In [30]:
model.linear.weight.dtype

torch.float32

In [31]:
y_train_tensor.dtype

torch.float32

In [32]:
model.parameters()

<generator object Module.parameters at 0x7908842d43c0>

## 4. Training Configuration
* **Hyperparameters:** The learning rate and number of training epochs are defined.
* **Loss Function:** `BCELoss` (Binary Cross-Entropy Loss) is selected to measure the difference between predicted probabilities and actual labels.
* **Optimizer:** Stochastic Gradient Descent (`SGD`) is used to update model weights.



In [33]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

   #zero gradient
  optimizer.zero_grad()


  #backward pass
  loss.backward()


  #parameter update
  optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 1.0016069412231445 
 2 , Loss = 0.6809680461883545 
 3 , Loss = 0.5186008214950562 
 4 , Loss = 0.43310290575027466 
 5 , Loss = 0.3800950050354004 
 6 , Loss = 0.3433142304420471 
 7 , Loss = 0.3159215450286865 
 8 , Loss = 0.2945151627063751 
 9 , Loss = 0.277194082736969 
 10 , Loss = 0.2628045082092285 
 11 , Loss = 0.250601589679718 
 12 , Loss = 0.24008086323738098 
 13 , Loss = 0.23088721930980682 
 14 , Loss = 0.22276274859905243 
 15 , Loss = 0.21551483869552612 
 16 , Loss = 0.2089967280626297 
 17 , Loss = 0.20309406518936157 
 18 , Loss = 0.19771632552146912 
 19 , Loss = 0.19279086589813232 
 20 , Loss = 0.18825843930244446 
 21 , Loss = 0.18407027423381805 
 22 , Loss = 0.1801857054233551 
 23 , Loss = 0.1765705794095993 
 24 , Loss = 0.17319591343402863 
 25 , Loss = 0.17003686726093292 


## 5. Evaluation & Summary
* **Model Evaluation:** Accuracy is calculated on the test set. Predictions are binarized (using a $0.9$ threshold) before being compared to true labels.
* **Model Summary:** The `torchinfo` library provides a detailed view of the architecture, including the number of trainable parameters.

In [34]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6098799705505371


### Summary

In [35]:
X_train_tensor.shape

torch.Size([455, 30])

In [36]:
!pip install torchinfo

In [37]:
from torchinfo import summary

In [38]:
summary(model, input_size = (455,30))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06